name: Build Code On Push

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-
      
      - name: Get .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.0.x'
        
      - name: Restore dependencies
        run: dotnet restore
        
      - name: Build
        run: dotnet build --configuration Release

      - name: StyleCop Check
        run: dotnet build /p:StyleCopEnabled=true

      - name: Print build success message
        run: echo "The repo successfully built!! :) "

      - name: Run tests
        run: dotnet test --no-build --verbosity normal

      - name: Print test success message
        run: echo "If you make it this far all of your tests are passing "

      - name: Publish
        run: dotnet publish -c Release -o out
  
      - name: Decode publish profile
        env:
          PUBLISH_PROFILE: ${{ secrets.PUBLISH_PROFILE }}
        run: |
          echo $PUBLISH_PROFILE | base64 --decode > /tmp/publish-profile.pubxml
  
      - name: Save build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: published-artifacts
          path: out/

